name: workflow

on:
  workflow_dispatch: 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a sample script
        run: echo "Hello from GitHub Actions!"
  build-c:
    needs: build
    runs-on: windows-2022

    steps:
        - run: echo "hi there"
  package:
    needs: [build , build-c]
    runs-on: macos-latest

    steps:
        - run: echo "hello"


        

